# Generated by Django 5.0 on 2023-12-25 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_usertoken2_password_alter_usertoken2_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserToken2',
            new_name='UserRefreshToken',
        ),
        migrations.RenameField(
            model_name='userrefreshtoken',
            old_name='password',
            new_name='token',
        ),
    ]
