# Generated by Django 5.0 on 2023-12-25 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_userrefreshtoken_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrefreshtoken',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
